// flow-typed signature: 8082217c4d8d8c871f80b9cea584c696
// flow-typed version: <<STUB>>/gulp-nf-prettier_v^2.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-nf-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-nf-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-nf-prettier/index' {
  declare module.exports: $Exports<'gulp-nf-prettier'>;
}
declare module 'gulp-nf-prettier/index.js' {
  declare module.exports: $Exports<'gulp-nf-prettier'>;
}
