// flow-typed signature: 7f298e692ef2adcf9f827d93f212b1d4
// flow-typed version: <<STUB>>/gulp-jasmine-browser_v^1.9.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-jasmine-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-jasmine-browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-jasmine-browser/lib/boot' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/drivers/chrome' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/drivers/phantomjs' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/drivers/phantomjs1' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/drivers/slimerjs' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/headless' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/helper' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/reporters/add_profile_reporter' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/reporters/add_sourcemapped_stacktrace_reporter' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/runners/chrome_evaluate' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/runners/phantom_runner' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/runners/slimer_runner' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/server' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/lib/spec_runner' {
  declare module.exports: any;
}

declare module 'gulp-jasmine-browser/webpack/jasmine-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-jasmine-browser/index' {
  declare module.exports: $Exports<'gulp-jasmine-browser'>;
}
declare module 'gulp-jasmine-browser/index.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser'>;
}
declare module 'gulp-jasmine-browser/lib/boot.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/boot'>;
}
declare module 'gulp-jasmine-browser/lib/drivers/chrome.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/drivers/chrome'>;
}
declare module 'gulp-jasmine-browser/lib/drivers/phantomjs.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/drivers/phantomjs'>;
}
declare module 'gulp-jasmine-browser/lib/drivers/phantomjs1.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/drivers/phantomjs1'>;
}
declare module 'gulp-jasmine-browser/lib/drivers/slimerjs.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/drivers/slimerjs'>;
}
declare module 'gulp-jasmine-browser/lib/headless.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/headless'>;
}
declare module 'gulp-jasmine-browser/lib/helper.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/helper'>;
}
declare module 'gulp-jasmine-browser/lib/reporters/add_profile_reporter.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/reporters/add_profile_reporter'>;
}
declare module 'gulp-jasmine-browser/lib/reporters/add_sourcemapped_stacktrace_reporter.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/reporters/add_sourcemapped_stacktrace_reporter'>;
}
declare module 'gulp-jasmine-browser/lib/runners/chrome_evaluate.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/runners/chrome_evaluate'>;
}
declare module 'gulp-jasmine-browser/lib/runners/phantom_runner.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/runners/phantom_runner'>;
}
declare module 'gulp-jasmine-browser/lib/runners/slimer_runner.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/runners/slimer_runner'>;
}
declare module 'gulp-jasmine-browser/lib/server.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/server'>;
}
declare module 'gulp-jasmine-browser/lib/spec_runner.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/lib/spec_runner'>;
}
declare module 'gulp-jasmine-browser/webpack/jasmine-plugin.js' {
  declare module.exports: $Exports<'gulp-jasmine-browser/webpack/jasmine-plugin'>;
}
