// flow-typed signature: b1bc04f9e460efbd301eb253acd83c33
// flow-typed version: <<STUB>>/through2-sink_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'through2-sink'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'through2-sink' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'through2-sink/index' {
  declare module.exports: $Exports<'through2-sink'>;
}
declare module 'through2-sink/index.js' {
  declare module.exports: $Exports<'through2-sink'>;
}
